{
 "title": "Kubernetes Overview",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"monitoring/kube-state-metrics\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by (node) (kube_pod_info))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by (namespace) (kube_namespace_status_phase))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n    max by (cluster, namespace, workload, workload_type, asserts_env, asserts_site) (\n      # replicaset\n      max by (cluster, namespace, replicaset, asserts_env, asserts_site) (last_over_time((kube_replicaset_spec_replicas{namespace=~\"$namespace\", replicaset=~\".+\"})[$__range:]))\n      * on (cluster, namespace, replicaset) group_left (workload, workload_type)\n      label_replace(\n          label_replace(\n              max by (cluster, namespace, replicaset) (last_over_time((kube_replicaset_owner{namespace=~\"$namespace\", replicaset=~\".+\", owner_kind=\"\"})[$__range:]))\n              , \"workload\", \"$1\", \"replicaset\", \"(.+)\"\n          )\n          , \"workload_type\", \"replicaset\", \"\", \"\"\n      )\n\n      OR\n\n      # deployment (kube_replicaset)\n      max by (cluster, namespace, replicaset, asserts_env, asserts_site) (last_over_time((kube_replicaset_spec_replicas{namespace=~\"$namespace\", replicaset=~\".+\"})[$__range:]))\n      * on (cluster, namespace, replicaset) group_left (workload, workload_type)\n      label_replace(\n          label_replace(\n              max by (cluster, namespace, replicaset, owner_name) (last_over_time((kube_replicaset_owner{namespace=~\"$namespace\", replicaset=~\".+\", owner_is_controller=\"true\", owner_kind=\"Deployment\", owner_name!=\"\"})[$__range:]))\n              , \"workload\", \"$1\", \"owner_name\", \"(.+)\"\n          )\n          , \"workload_type\", \"deployment\", \"\", \"\"\n      )\n\n      OR\n\n      # deployment (kube_deployment)\n      label_replace(\n        label_replace(\n            max by (cluster, namespace, deployment, asserts_env, asserts_site) (last_over_time((kube_deployment_spec_replicas{namespace=~\"$namespace\", deployment=~\".+\"})[$__range:]))\n            , \"workload\", \"$1\", \"deployment\", \"(.+)\"\n        )\n        , \"workload_type\", \"deployment\", \"\", \"\"\n      )\n\n      OR\n\n      # daemonset\n      label_replace(\n          label_replace(\n              max by (cluster, namespace, daemonset, asserts_env, asserts_site) (last_over_time((kube_daemonset_status_desired_number_scheduled{namespace=~\"$namespace\", daemonset=~\".+\"})[$__range:]))\n              , \"workload\", \"$1\", \"daemonset\", \"(.+)\"\n          )\n      , \"workload_type\", \"daemonset\", \"\", \"\"\n      )\n\n      OR\n\n      # statefulset\n      label_replace(\n          label_replace(\n              max by (cluster, namespace, statefulset, asserts_env, asserts_site) (last_over_time((kube_statefulset_replicas{namespace=~\"$namespace\", statefulset=~\".+\"})[$__range:]))\n              , \"workload\", \"$1\", \"statefulset\", \"(.+)\"\n          )\n      , \"workload_type\", \"statefulset\", \"\", \"\"\n      )\n\n      OR\n\n      # everything else\n      last_over_time((namespace_workload_pod:kube_pod_owner:relabel{\n        namespace=~\".+\",\n        workload=~\".+\",\n        workload_type!=\"replicaset\",\n        workload_type!=\"deployment\",\n        workload_type!=\"daemonset\",\n        workload_type!=\"statefulset\"\n      })[$__range:])\n    )\n    )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by (cluster, namespace, pod) (kube_pod_info{namespace=~\"$namespace\", pod!=\"\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by (cluster, namespace, pod, container) (kube_pod_container_info{namespace=~\"$namespace\", pod!=\"\", container!=\"POD\", container!=\"\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "  sum(\n    label_join(\n          max by (instance) (node_memory_Active_file_bytes)\n        + on (instance) group_left ()\n          max by (instance) (node_memory_AnonPages_bytes)\n      or\n        max by (instance) (node_memory_working_set_bytes),\n      \"node\",\n      \",\",\n      \"instance\"\n    )\n  )",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "  sum(\n    label_join(\n          sum by (instance) (\n            max by (instance, cpu, core) (1 - rate(node_cpu_seconds_total{mode=~\"idle\"}[$__rate_interval]) >= 0)\n          )\n        or\n          sum by (instance) (rate(node_cpu_usage_seconds_total[$__rate_interval]) >= 0)\n      or\n        sum by (instance) (\n          label_join(\n            label_join(k8s_node_cpu_usage, \"cluster\", \",\", \"k8s_cluster_name\"),\n            \"instance\",\n            \",\",\n            \"k8s_node_name\"\n          )\n        ),\n      \"node\",\n      \",\",\n      \"instance\"\n    )\n  )\n/ on (cluster)\n  sum by (cluster) (\n      sum by (cluster) (max by (node, resource) (kube_node_status_capacity{resource=~\"cpu\"}))\n    or\n      sum by (cluster) (\n        label_join(\n          label_join(system_cpu_logical_count, \"cluster\", \",\", \"k8s_cluster_name\"),\n          \"node\",\n          \",\",\n          \"k8s_node_name\"\n        )\n      )\n  )",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "last_over_time((max by (asserts_env, asserts_site, cluster, container_runtime_version, internal_ip, kernel_version, kubelet_version, node, os_image, pod_cidr, provider_id, system_uuid) (kube_node_info{node=~\".+\"}))[$__range:])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time((sum by (cluster, node) (label_join(sum by (cluster, instance) (max by (cluster, instance, cpu, core) (1 - rate(node_cpu_seconds_total{instance=~\".+\", mode=~\"idle\"}[$__rate_interval]) >= 0)) or sum by (cluster, instance) (rate(node_cpu_usage_seconds_total{instance=~\".+\"}[$__rate_interval]) >= 0) or sum by (cluster, instance) (label_join(label_join(k8s_node_cpu_usage, \"cluster\", \",\", \"k8s_cluster_name\"), \"instance\", \",\", \"k8s_node_name\")), \"node\", \",\", \"instance\")))[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}