###############################################################
# Receivers configuration
# https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver
###############################################################
receivers:
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/k8seventsreceiver/README.md
  k8s_events:
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/README.md
  prometheus:
    target_allocator:
      endpoint: http://opentelemetry-target-allocator-ta.monitoring.svc.cluster.local
      interval: 30s
      collector_id: ${OTEL_K8S_POD_NAME}

  # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/k8sobjectsreceiver/README.md
  k8s_objects:
    auth_type: serviceAccount
    include_initial_state: true
    objects:
      - name: verticalpodautoscalers
        mode: watch
        group: autoscaling.k8s.io

processors:
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/transformprocessor/README.md
  transform/k8s_objects:
    error_mode: ignore
    log_statements:
      - context: log
        statements:
          - set(resource.attributes["service.name"], "k8s_objects")
          - delete_key(body["object"]["metadata"], "managedFields") where IsMap(body)
          # Set severity text
          - set(severity_text, "INFO")
          # Set severity number
          - set(severity_number, SEVERITY_NUMBER_INFO)

  transform/k8s_vpa_objects:
    error_mode: ignore
    log_statements:
      - context: log
        conditions:
          - resource.attributes["k8s.resource.name"] == "verticalpodautoscalers"
        statements:
          # 1. Pull the container name out of the JSON body and elevate it to an attribute
          - set(attributes["k8s.container.name"], body["status"]["recommendation"]["containerRecommendations"]["containerName"])
          
          # 2. Extract the CPU string and clean it up (e.g., "25m" -> "25")
          - set(attributes["vpa_cpu_raw"], body["status"]["recommendation"]["containerRecommendations"]["target"]["cpu"])
          # replace_pattern replaces the regex match ("m") with an empty string ("")
          - replace_pattern(attributes["vpa_cpu_raw"], "m", "")
          
          # 3. Extract the Memory string and clean it up (e.g., "250Mi" -> "250")
          - set(attributes["vpa_mem_raw"], body["status"]["recommendation"]["containerRecommendations"]["target"]["memory"])
          # replace_pattern replaces the regex match ("Mi") with an empty string ("")
          - replace_pattern(attributes["vpa_mem_raw"], "Mi", "")


  transform/k8s_events:
    error_mode: ignore
    log_statements:
      - context: log
        statements:
          - set(resource.attributes["service.name"], "k8s_events")

connectors:
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/connector/signaltometricsconnector/README.md
  signaltometrics:
    logs:
      - name: k8s.vpa.target.cpu
        conditions:
          - resource.attributes["k8s.resource.name"] == "verticalpodautoscalers"
        description: "The VPA recommended target CPU in millicores"
        unit: "m"
        gauge:
          # Convert the string attribute we created into an Integer
          value: Int(attributes["vpa_cpu_raw"])
        attributes:
          # Simply map the key names. The connector automatically copies these to the metric.
          - key: k8s.container.name

      - name: k8s.vpa.target.memory
        conditions:
          - resource.attributes["k8s.resource.name"] == "verticalpodautoscalers"
        description: "The VPA recommended target memory in Megabytes"
        unit: "Mi"
        gauge:
          value: Int(attributes["vpa_mem_raw"])
        attributes:
          - key: k8s.container.name

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [memory_limiter, resource_detection]
      exporters: [prometheus_remote_write]
    logs:
      receivers: [k8s_events]
      processors: [memory_limiter, resource_detection, transform/k8s_events]
      exporters: [otlp_http/loki]
    logs/k8s_objects:
      receivers: [k8s_objects]
      processors: [memory_limiter, resource_detection, transform/k8s_objects, transform/k8s_vpa_objects]
      exporters: [otlp_http/loki, signaltometrics]

    metrics/vpa:
      receivers: [signaltometrics]
      processors: [memory_limiter]
      exporters: [debug]
