apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-assistant-app-cert
spec:
  secretName: home-assistant-app-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - hass.pontifex.dev

