services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token "${CLOUDFLARE_TUNNEL_TOKEN}"

    # Logging configuration for Cloudflare Tunnel container
    logging:
      driver: "json-file" # Use the default json-file logging driver
      options:
        max-size: "100m" # Maximum log file size before rotation (100 MB)
        max-file: "10" # Maximum number of log files to retain (10)

    restart: unless-stopped
    network_mode: host

    # Health check configuration to verify Cloudflare Tunnel readiness
    healthcheck:
      test: ["CMD", "cloudflared", "--version"] # Check if cloudflared version command works
      interval: 30s # Time between health check attempts
      timeout: 10s # Time to wait for a response
      retries: 3 # Number of retries before marking as unhealthy
      start_period: 10s # Delay before health checks begin
