loki:
  kustomize build --enable-helm loki | kubectl apply --server-side=true --filename -

prometheus:
  kustomize build --enable-helm prometheus | kubectl apply --server-side=true --filename -

otel:
  kustomize build --enable-helm opentelemetry-collector | kubectl apply --server-side=true --force-conflicts --filename -
