apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: otel-tui

namespace: monitoring

labels:
  - pairs:
      app.kubernetes.io/name: otel-tui
    includeSelectors: true

resources:
  - deployment.yaml
  - service.yaml
