# machine:
#   type: controlplane
#   network:
#     interfaces:
#       # https://docs.siderolabs.com/talos/v1.13/networking/advanced/vip#virtual-shared-ip
#       - interface: enp1s0 # Match your primary network interface name
#         dhcp: true
#         vip:
#           ip: 10.10.100.100 # desired Control Plane VIP
# ---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/refs/heads/main/pkg/machinery/config/schemas/config.schema.json
apiVersion: v1alpha1
kind: Layer2VIPConfig
name: 10.10.100.100
link: enp2s0
