apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: homelab-apps
  namespace: argocd
spec:
  description: Homelab User-Facing Applications
  sourceRepos:
    - https://github.com/damienpontifex/*
  destinations:
    - name: in-cluster
      namespace: argocd
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
