apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: homelab-apps
  namespace: argocd
spec:
  description: Homelab User-Facing Applications
  sourceRepos:
    - https://github.com/damienpontifex/homelab
    - https://github.com/damienpontifex/homelab.git
  destinations:
    - name: in-cluster
      namespace: homepage
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
