apiVersion: v1
kind: Service
metadata:
  name: matter-server
spec:
  type: ClusterIP
  ports:
    - name: matter-server
      protocol: TCP
      port: 5580
      targetPort: 5580
      appProtocol: kubernetes.io/wss

