resources:
  requests:
    cpu: 25m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Mi
crds:
  enabled: true
serviceAccount:
  annotations:
    azure.workload.identity/client-id: e9c44962-2ddb-4761-b8d5-a34e3d82d6ff
    azure.workload.identity/tenant-id: ff2b9041-8733-4fbd-a4e6-23f30567c4a4
config:
  logging:
    format: json
prometheus:
  servicemonitor:
    enabled: true
