global:
  domain: argocd.pontifex.dev
  logging:
    format: json

controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

server:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  service:
    type: LoadBalancer
    annotations:
      external-dns.alpha.kubernetes.io/hostname: argocd.pontifex.dev
  certificate:
    enabled: true
    issuer:
      group: cert-manager.io
      kind: ClusterIssuer
      name: letsencrypt-prod
  vpa:
    enabled: false #TODO: re-enable after installing VPA

configs:
  params:
    "server.insecure": "false"

  cm:
    "kustomize.buildOptions": "--enable-helm"
    "users.anonymous.enabled": "true"
  rbac:
    "policy.default": "role:org-admin"
    "policy.csv": |
      p, gethomepage, applications, *, */*, role:readonly
      p, role:org-admin, *, *, *, allow
    scopes: "[groups, email]"

