apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  # https://artifacthub.io/packages/helm/grafana/loki
  - repo: https://grafana.github.io/helm-charts
    name: loki
    version: 6.52.0
    releaseName: loki
    valuesFile: loki.values.yaml
    skipTests: true
