# yaml-language-server: $schema=https://github.com/adobe-platform/kubernetes-json-schema/raw/refs/heads/master/master-standalone/appproject-argoproj-v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core-services
  namespace: argocd
spec:
  description: Homelab Core Services
  sourceRepos:
    - https://github.com/damienpontifex/*
  destinations:
    - name: in-cluster
      namespace: argocd
    - name: in-cluster
      namespace: kube-system
    - name: in-cluster
      namespace: argocd
    - name: in-cluster
      namespace: external-dns
    - name: in-cluster
      namespace: cert-manager
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

