apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: homelab
  namespace: argocd
spec:
  description: pontifex.dev Homelab
  # Allow manifests to deploy from any Git repos under damienpontifex GitHub account
  sourceRepos:
    - https://github.com/damienpontifex/*
  # Allow deployment to any namespace on the cluster
  destinations:
    - namespace: '*'
      server: '*'
