apiVersion: admissionregistration.k8s.io/v1alpha1
kind: MutatingAdmissionPolicy
metadata:
  name: "auto-inject-otel"
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
  mutations:
    - patchType: "JSONPatch"
      jsonPatch:
        expression: |
          [
            {
              "op": "add",
              "path": "/metadata/annotations/instrumentation.opentelemetry.io~1inject-sdk",
              "value": "true"
            }
          ]
