###############################################################
# Processors configuration
# https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor
###############################################################
processors:
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
  resource_detection:
    detectors: [env, system]

exporters:
  # https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/debugexporter/README.md
  debug:
    verbosity: detailed
  # https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/otlphttpexporter/README.md
  otlp_http/prometheus:
    endpoint: http://prometheus-server.monitoring.svc.cluster.local/api/v1/otlp
  # https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/otlphttpexporter/README.md
  otlp_http/loki:
    endpoint: http://loki-gateway.monitoring.svc.cluster.local/otlp

extensions:
  health_check:
    endpoint: ${env:MY_POD_IP}:13133

