apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

configMapGenerator:
  - files: 
    - relay=daemonset/otel-config.yaml
    - common=common-otel-config.yaml
    name: otel-collector-daemonset-config
  - files:
    - relay=deployment/otel-config.yaml
    - common=common-otel-config.yaml
    name: otel-collector-deployment-config

helmCharts:
  # https://artifacthub.io/packages/helm/opentelemetry-helm/opentelemetry-collector
  - &otel-common
    name: opentelemetry-collector
    repo: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.165.0
    namespace: monitoring
    releaseName: opentelemetry-collector-deployment
    valuesFile: common-values.yaml
    additionalValuesFiles:
      - deployment/values.yaml

  - <<: *otel-common
    releaseName: opentelemetry-collector-daemonset
    additionalValuesFiles:
    - daemonset/values.yaml

  # https://artifacthub.io/packages/helm/prometheus-community/prometheus-operator-crds
  # - repo: oci://ghcr.io/prometheus-community/charts
  #   name: prometheus-operator-crds
  #   version: 27.0.0
  #   releaseName: prometheus-operator-crds
  #
  # # https://artifacthub.io/packages/helm/opentelemetry-helm/opentelemetry-target-allocator
  # - repo: https://open-telemetry.github.io/opentelemetry-helm-charts
  #   name: opentelemetry-target-allocator
  #   # renovate: datasource=helm registryUrl=https://open-telemetry.github.io/opentelemetry-helm-charts depName=opentelemetry-target-allocator
  #   version: 0.126.10
  #   releaseName: opentelemetry-target-allocator
  #   valuesFile: opentelemetry-target-allocator-values.yaml
  #
  # https://artifacthub.io/packages/helm/opentelemetry-helm/opentelemetry-kube-stack
  # - repo: https://open-telemetry.github.io/opentelemetry-helm-charts
  #   name: opentelemetry-kube-stack
  #   # renovate: datasource=helm registryUrl=https://open-telemetry.github.io/opentelemetry-helm-charts depName=opentelemetry-kube-stack
  #   version: 0.17.1
  #   releaseName: opentelemetry-kube-stack
  #   valuesFile: opentelemetry-kube-stack-values.yaml
  #   includeCRDs: true
  #   namespace: monitoring
