set shell := ["bash", "-c"]
root_dir := justfile_dir()
endpoints := "10.10.100.2"
nodes := "10.10.100.2"

# List all available commands
list:
	just --list

_talosctl command *FLAGS:
	talosctl {{command}} \
		--nodes {{nodes}} \
		--endpoints {{endpoints}} \
		--talosconfig=./clusterconfig/talosconfig \
		{{FLAGS}}

# Provide a text-based UI to navigate node overview, logs and real-time metrics.
[group("monitoring")]
dashboard: (_talosctl "dashboard")

[group("monitoring")]
health: (_talosctl "health")

# [group("dev")]
# upgrade-k8s: genconfig
# 	talhelper gencommand upgrade-k8s | sh
#
# [group("dev")]
# upgrade: genconfig
# 	talhelper gencommand upgrade | sh

# Apply a new configuration to a node
[group("dev")]
apply *FLAGS: genconfig
	for control in "{{root_dir}}/patches/nodes/control-*.yaml"; do \
		just _talosctl "apply-config" --file ./clusterconfig/controlplane.yaml --config-patch $control {{FLAGS}}; \
	done

# Generate Talos cluster config YAML files
[group("dev")]
genconfig cluster_name="homelab":
	@git clean -xf ./clusterconfig; \
	talosctl gen config {{cluster_name}} https://{{endpoints}}:6443 \
		--kubernetes-version 1.36.2 \
		--talos-version 1.13.6 \
		--with-secrets <(sops --decrypt secrets.sops.yaml) \
		--config-patch @patches/global.yaml \
		--config-patch-control-plane @patches/controlplane.yaml \
		--config-patch-worker @patches/worker.yaml \
		--output ./clusterconfig

bootstrap:
	just apply --insecure; \
	# Wait until fails to connect to talos API server indicating restarting
	while nc -z -w 1 {{nodes}} 50000; do; sleep 1; done; \
	# Wait until can connect again indicating back up
	until nc -z -w 1 {{nodes}} 50000; do; sleep 1; done; \
	# Bootstrap etcd
	just _talosctl "bootstrap"; \
	# Get kubeconfig
	just kubeconfig; \
	# Apply cilium
	just apply-cilium; \
	# Apply external-secrets
	just apply-external-secrets; \
	# Apply prometheus-crds
	just apply-prometheus-crds;

# Add kubeconfig
[group("ops")]
kubeconfig: genconfig
	@just _talosctl "kubeconfig" --force

# reset:
# 	@just _talosctl ""

# See if a TCP connection to the node on port 50,000 is possible
[group("monitoring")]
check-connection:
	nc -zv $(yq '.contexts.homelab.endpoints[0]' ./clusterconfig/talosconfig) 50000

[group("maintenance")]
reboot:
	@just _talosctl reboot

[group("maintenance")]
shutdown:
	@just _talosctl shutdown

# Bootstrap Cilium CNI
apply-cilium:
	kustomize build --enable-helm ../apps/01-system-core/cilium/ \
		| kubectl apply --server-side=true --filename -
	until kustomize build --enable-helm ../apps/01-system-core/cilium-resources/ \
		| kubectl apply --server-side=true --filename -; do \
		sleep 5; \
	done

# Bootstrap external secrets in the cluster
apply-external-secrets:
	#!/usr/bin/env bash
	kubectl create namespace external-secrets || true

	function kv-secret() {
		local name=$1
		az keyvault secret show --name $name --vault-name pontifex-homelab --query 'value' --output tsv
	}
	kubectl create secret generic azure-kv-sp \
		--namespace external-secrets \
		--from-literal ClientID=$(kv-secret external-secrets-client-id) \
		--from-literal ClientSecret=$(kv-secret external-secrets-client-secret) || true

	unset -f kv-secret

	until kustomize build --enable-helm ../apps/01-system-core/external-secrets | kubectl apply --server-side=true --filename -; do
		# n.b. cluster secret store resource will fail until pods have started
		sleep 5
	done

# Bootstrap prometheus types
apply-prometheus-crds:
	kustomize build --enable-helm ../apps/01-system-core/prometheus-crds/ \
		| kubectl apply --server-side=true --filename -

apply-argocd:
	kustomize build --enable-helm ../apps/01-system-core/argocd \
		| kubectl apply --server-side=true --filename -
