set shell := ["bash", "-c"]
root_dir := justfile_dir()

# List all available commands
list:
	just --list

_talosctl command *FLAGS:
	talosctl {{command}} \
		--nodes 10.10.100.2 \
		--endpoints 10.10.100.2 \
		--talosconfig=./talosconfig \
		{{FLAGS}}

# Provide a text-based UI to navigate node overview, logs and real-time metrics.
[group("monitoring")]
dashboard: (_talosctl "dashboard")

[group("monitoring")]
health: (_talosctl "health")

# [group("dev")]
# upgrade-k8s: genconfig
# 	talhelper gencommand upgrade-k8s | sh
#
# [group("dev")]
# upgrade: genconfig
# 	talhelper gencommand upgrade | sh

# Apply a new configuration to a node
[group("dev")]
apply *FLAGS:
	@for control in "{{root_dir}}/patches/nodes/control-*.yaml"; do \
		just genconfig $control; \
		just _talosctl "apply-config" --file ./clusterconfig/$(basename "$control") {{FLAGS}}; \
	done

# Generate Talos cluster config YAML files
[group("dev")]
genconfig node_patch cluster_name="homelab" ip="10.10.100.2":
	@git clean -xf ./clusterconfig; \
	talosctl gen config {{cluster_name}} https://{{ip}}:6443 \
		--kubernetes-version 1.36.2 \
		--talos-version 1.13.6 \
		--with-secrets <(sops --decrypt secrets.sops.yaml) \
		--config-patch-control-plane @patches/controlplane.yaml \
		--config-patch @patches/global.yaml \
		--config-patch @{{node_patch}} \
		--output-types controlplane \
		--output ./clusterconfig/$(basename {{node_patch}})

# Add kubeconfig
[group("ops")]
kubeconfig:
	talhelper gencommand kubeconfig | sh

reset:
	talhelper gencommand reset --extra-flags --reboot | sh

# See if a TCP connection to the node on port 50,000 is possible
[group("monitoring")]
check-connection:
	nc -zv $(yq '.contexts.homelab.endpoints[0]' ./clusterconfig/talosconfig) 50000

[group("maintenance")]
reboot:
	@just _talosctl reboot

[group("maintenance")]
shutdown:
	@just _talosctl shutdown

apply-cilium:
	kustomize build --enable-helm ../apps/01-system-core/cilium/ \
		| kubectl apply --server-side=true --filename - --kubeconfig=./kubeconfig
	kustomize build --enable-helm ../apps/01-system-core/cilium-resources/ \
		| kubectl apply --server-side=true --filename - --kubeconfig=./kubeconfig
# k exec -it -n kube-system cilium-lhg9v -- cilium bgp peers

apply-policies:
	kustomize build --enable-helm ../apps/01-system-core/admission/ \
		| kubectl apply --server-side=true --filename - --kubeconfig=./kubeconfig

apply-argocd:
	kustomize build --enable-helm ../apps/01-system-core/argocd \
		| kubectl apply --server-side=true --filename - --kubeconfig=./kubeconfig

apply-cloudflare-tunnel:
	# Need tunnel in place so that external secrets can validate the issuer
	kubectl --kubeconfig=./kubeconfig apply --server-side=true --filename ../apps/02-core-services/cloudflare-tunnel/namespace.yaml
	# Get the secret manually to bootstrap and external secrets will manage afterwards
	kubectl --kubeconfig=./kubeconfig create secret generic cloudflare-api-token \
		--namespace cloudflare-tunnel \
		--from-literal=token=$(az keyvault secret show --name cloudflare-api-token --vault-name pontifex-homelab --query 'value' --output tsv) || true
	# Apply the role and deployment to make this happen
	# kubectl --kubeconfig=./kubeconfig apply --server-side=true --filename ../apps/02-core-services/cloudflare-tunnel/jwk-discovery.yaml
	# kubectl --kubeconfig=./kubeconfig apply --server-side=true --filename ../apps/02-core-services/cloudflare-tunnel/cloudflare-tunnel.yaml

