apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cilium

namespace: kube-system

resources:
  - cilium-gateway.yaml

helmCharts:
  # https://artifacthub.io/packages/helm/cilium/cilium
  - name: cilium
    repo: https://helm.cilium.io/
    releaseName: cilium
    namespace: kube-system
    valuesFile: cilium.values.yaml
    # renovate: datasource=helm registryUrl=https://helm.cilium.io/ depName=cilium
    version: 1.19.5
