datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      # https://grafana.com/docs/grafana/latest/datasources/loki/
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.monitoring.svc.cluster.local:3100
        isDefault: false
      # https://grafana.com/docs/grafana/latest/datasources/prometheus/
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true
      # https://grafana.com/docs/grafana/latest/datasources/tempo/
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo.monitoring.svc.cluster.local:3200
        isDefault: false
      - name: Strava
        type: grafana-strava-datasource
        access: proxy
        isDefault: false
        jsonData:
          clientID: 102977
        secureJsonData:
          clientSecret: ${STRAVA_CLIENT_SECRET}

plugins:
  # https://grafana.com/grafana/plugins/grafana-strava-datasource/
  - grafana-strava-datasource
        

# Ref: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/
grafana.ini:
  server:
    root_url: http://localhost
  # ========================================================================
  # Logging
  # ========================================================================
  log:
    mode: console
    level: info
  log.console:
  format: json
  # ========================================================================
  # Authentication
  # https://grafana.com/docs/grafana/latest/setup-grafana/configure-access/configure-authentication/entraid/
  # ========================================================================
  auth.anonymous:
    enabled: true
    org_role: Admin

  feature_toggles:
    # Git sync https://grafana.com/docs/grafana/latest/as-code/observability-as-code/git-sync/git-sync-setup/set-up-before/
    provisioning: true
    # For strava plugin
    externalServiceAccounts: true

  panels:
    enable_alpha: true

service:
  type: LoadBalancer
  annotations:
    external-dns.alpha.kubernetes.io/hostname: grafana.pontifex.dev
    
# kubectl create secret generic grafana-secrets --namespace monitoring --from-literal=STRAVA_CLIENT_SECRET=$(pbpaste)
envFromSecret: grafana-secrets

persistence:
  enabled: true
securityContext:
  runAsUser: 472
  runAsGroup: 472
  fsGroup: 472

initChownData:
  enabled: false # Disable the container causing the error

sidecar:
  dashboards:
    enabled: true
    searchNamespace: ALL
  datasources:
    enabled: false
    searchNamespace: ALL

# Mounting the certificate from cert-manager
# 1. Mount the secret files into the pod container
extraContainers: []
extraVolumeMounts:
  - name: tls-certs
    mountPath: /etc/grafana/tls
    readOnly: true

extraVolumes:
  - name: tls-certs
    secret:
      secretName: grafana-app-tls-secret

# 2. Configure Grafana to use the mounted certificates
grafana.ini:
  server:
    protocol: https
    cert_file: /etc/grafana/tls/tls.crt
    cert_key: /etc/grafana/tls/tls.key
