apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  # https://artifacthub.io/packages/helm/prometheus-community/prometheus
  - repo: oci://ghcr.io/prometheus-community/charts
    name: prometheus
    version: 28.9.0
    releaseName: prometheus
    valuesFile: prometheus.values.yaml
