apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system-core
  namespace: argocd
spec:
  description: Homelab System Core (Cilium, External Secrets, Storage)
  sourceRepos:
    - https://github.com/damienpontifex/homelab
    - https://github.com/damienpontifex/homelab.git
  destinations:
    - name: in-cluster
      namespace: kube-system
    - name: in-cluster
      namespace: local-path-provisioner
    - name: in-cluster
      namespace: external-secrets
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
