machine:
  type: controlplane
  install:
    diskSelector:
      wwid: "naa.50014ee20d45f411"
    wipe: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/refs/heads/main/pkg/machinery/config/schemas/config.schema.json
apiVersion: v1alpha1
kind: HostnameConfig
hostname: homelab-control-01
auto: off
