###############################################################
# Receivers configuration
# https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver
###############################################################
receivers:
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kubeletstatsreceiver/README.md
  kubelet_stats:
    collection_interval: 20s
    auth_type: serviceAccount
    endpoint: https://${env:OTEL_K8S_NODE_NAME}:10250
    node: ${env:OTEL_K8S_NODE_NAME}
    insecure_skip_verify: true
    k8s_api_config:
      auth_type: serviceAccount
    metric_groups:
    - node
    - pod
    - container
    - volume
    metrics:
      k8s.container.cpu.node.utilization:
        enabled: true
      k8s.pod.cpu.node.utilization:
        enabled: true
      k8s.container.memory.node.utilization:
        enabled: true
      k8s.pod.memory.node.utilization:
        enabled: true

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [kubelet_stats]
      processors: [memory_limiter, resource_detection]
      exporters: [otlp_http/prometheus]

