# yaml-language-server: $schema=https://raw.githubusercontent.com/open-telemetry/opentelemetry-helm-charts/refs/heads/main/charts/opentelemetry-collector/values.schema.json
mode: daemonset

extraVolumes:
  - name: otel-collector-config
    configMap:
      name: otel-collector-daemonset-config

clusterRole:
  create: true
  rules:
  - apiGroups: [""]
    resources: ["nodes/stats"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]

  # Only needed if you are using extra_metadata_labels or
  # are collecting the request/limit utilization metrics
  - apiGroups: [""]
    resources: ["nodes/pods"]
    verbs: ["get"]

  # Only needed if you are using k8s_api_config to collect
  # detailed volume metadata from PersistentVolumeClaims
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get"]


# https://opentelemetry.io/docs/platforms/kubernetes/helm/collector/#presets
presets:
  # Configures some default things for us
  kubeletMetrics:
    enabled: true
#   kubernetesAttributes:
#     enabled: true
#   logsCollection:
#     enabled: true
#     includeCollectorLogs: false
#   # TODO: which handles https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8sobjectsreceiver

