# yaml-language-server: $schema=https://raw.githubusercontent.com/adobe-platform/kubernetes-json-schema/refs/heads/master/master-standalone-strict/clustersecretstore-external-secrets-v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: homelab
spec:
  provider:
    azurekv:
      tenantId: ff2b9041-8733-4fbd-a4e6-23f30567c4a4
      vaultUrl: https://pontifex-homelab.vault.azure.net/
      authSecretRef:
        clientId:
          name: azure-kv-sp
          key: ClientID
          namespace: external-secrets
        clientSecret:
          name: azure-kv-sp
          key: ClientSecret
          namespace: external-secrets
