# yaml-language-server: $schema=https://raw.githubusercontent.com/adobe-platform/kubernetes-json-schema/refs/heads/master/master-standalone-strict/clustersecretstore-external-secrets-v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: homelab
spec:
  provider:
    azurekv:
      vaultUrl: https://pontifex-homelab.vault.azure.net/
      authType: WorkloadIdentity
