name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install kubect-validate
        run: |
          cd $(mktemp -d)
          curl --location \
            https://github.com/kubernetes-sigs/kubectl-validate/releases/latest/download/kubectl-validate_linux_amd64.tar.gz \
            | tar --extract --gzip kubectl-validate
          echo "$PWD" >> $GITHUB_PATH

      - name: Install Task
        uses: go-task/setup-task@v1

      - name: Validate kustomizations
        run: task validate
